version: '3.9'
services:
  web:
    image: ozgurozturknet/web
    networks:
      - my-bridge
    ports:
      - "8080:80"
  db:
    image: ozgurozturknet/fakedb
    networks:
      - my-bridge
networks:
  my-bridge:
    driver: bridge